# Generated by Django 4.1 on 2022-08-24 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time', models.FloatField(default=5)),
                ('used_time', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchTiming',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('current_timer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_timer', to='user_activity.timer')),
                ('previous_timers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_timers', to='user_activity.timer')),
            ],
        ),
    ]
