# Generated by Django 4.1 on 2022-08-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity', '0003_alter_previoustimers_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='previoustimers',
            name='availed_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timer',
            name='availed_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='previoustimers',
            name='total_time',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='timer',
            name='total_time',
            field=models.FloatField(default=2),
        ),
    ]
