# Generated by Django 4.1 on 2022-08-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(max_length=50)),
                ('family_name', models.CharField(default='', max_length=50)),
                ('given_name', models.CharField(default='', max_length=50)),
                ('picture', models.CharField(default='https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp&f=y', max_length=255)),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('locale', models.CharField(default='en-us', max_length=50)),
                ('password', models.CharField(default='', max_length=255)),
                ('refresh', models.CharField(default='', max_length=512)),
                ('playlist', models.CharField(default='PLwajP6X62-C5jtqbacQD4YElNnMOj1tFK', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
