# Generated by Django 4.0.6 on 2022-07-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('imageUrl', models.CharField(default='https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp&f=y', max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=255)),
                ('refresh', models.CharField(max_length=512, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
