# Generated by Django 4.0.6 on 2022-07-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
