# Generated by Django 4.1 on 2022-08-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='playlist',
            field=models.CharField(default='', max_length=255),
        ),
    ]
