# Generated by Django 4.0.6 on 2022-08-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='imageUrl',
            new_name='picture',
        ),
        migrations.AddField(
            model_name='user',
            name='family_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='given_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(default='en-us', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='refresh',
            field=models.CharField(default='', max_length=512),
        ),
    ]
