# Generated by Django 4.0.6 on 2022-07-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_uid_user_openid_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='openid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='imageUrl',
            new_name='picture',
        ),
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(default='en-us', max_length=50),
        ),
    ]
