# Generated by Django 4.0.6 on 2022-08-01 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='expiry',
        ),
    ]
